// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LogInLogOutTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void logInLogOut() {
    driver.Navigate().GoToUrl("https://qauto2.forstudy.space/");
    driver.Manage().Window.Size = new System.Drawing.Size(1051, 720);
    driver.FindElement(By.CssSelector(".btn-outline-white")).Click();
    driver.FindElement(By.Id("signinEmail")).SendKeys("warlam4ik@i.ua");
    driver.FindElement(By.Id("signinPassword")).SendKeys("Test12345");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(2)")).Click();
    driver.FindElement(By.LinkText("Log out")).Click();
  }
}
