// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SignUpTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void signUp() {
    driver.Navigate().GoToUrl("https://qauto2.forstudy.space/");
    driver.Manage().Window.Size = new System.Drawing.Size(1053, 720);
    driver.FindElement(By.CssSelector(".hero-descriptor_btn")).Click();
    driver.FindElement(By.Id("signupName")).Click();
    driver.FindElement(By.Id("signupName")).SendKeys("wwwwwwwwwwwwwww");
    driver.FindElement(By.Id("signupLastName")).Click();
    driver.FindElement(By.Id("signupLastName")).SendKeys("wwwwwwwwwwwww");
    driver.FindElement(By.Id("signupEmail")).Click();
    driver.FindElement(By.Id("signupEmail")).SendKeys("wwwwwwww@ww.ww");
    driver.FindElement(By.Id("signupPassword")).Click();
    driver.FindElement(By.Id("signupPassword")).SendKeys("Passworddd123");
    driver.FindElement(By.Id("signupRepeatPassword")).Click();
    driver.FindElement(By.Id("signupRepeatPassword")).SendKeys("Passworddd123");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
  }
}
